/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'rouletteStats' : GameStats,
  'slotsStats' : GameStats,
  'houseProfit' : bigint,
  'hiloStats' : GameStats,
  'aviatorStats' : GameStats,
  'teenPattiStats' : GameStats,
  'totalWagered' : bigint,
  'totalPaidOut' : bigint,
  'totalUsers' : bigint,
}
export interface GameStats {
  'totalWagered' : bigint,
  'totalPaidOut' : bigint,
  'playCount' : bigint,
}
export interface LoginResult {
  'success' : boolean,
  'balance' : bigint,
  'message' : string,
}
export interface PlayerWallet {
  'username' : string,
  'balance' : bigint,
}
export interface UserCredential {
  'username' : string,
  'password' : string,
  'balance' : bigint,
}
export interface HiLoResult {
  'win' : boolean,
  'message' : string,
  'newCard' : bigint,
  'payout' : bigint,
}
export interface MultiPlayResult {
  'win' : boolean,
  'result' : bigint,
  'message' : string,
  'totalPayout' : bigint,
}
export interface PlayResult {
  'win' : boolean,
  'result' : bigint,
  'message' : string,
  'payout' : bigint,
}
export interface AviatorResult {
  'win' : boolean,
  'payout' : bigint,
  'crashPoint' : bigint,
  'message' : string,
}
export interface TeenPattiResult {
  'win' : boolean,
  'payout' : bigint,
  'playerCards' : Array<bigint>,
  'dealerCards' : Array<bigint>,
  'playerRank' : bigint,
  'dealerRank' : bigint,
  'message' : string,
}
export interface RouletteBet {
  'betType' : string,
  'betValue' : bigint,
  'wager' : bigint,
}
export interface SlotsResult {
  'win' : boolean,
  'message' : string,
  'reels' : Array<bigint>,
  'payout' : bigint,
}
export interface UserProfile {
  'balance' : bigint,
  'totalWagered' : bigint,
  'totalWon' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStatProfile {
  'principal' : string,
  'balance' : bigint,
  'totalWagered' : bigint,
  'totalWon' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAdjustBalance' : ActorMethod<[string, bigint, boolean], string>,
  'adminCreateUser' : ActorMethod<[string, string], string>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserStatProfile>>,
  'adminGetCreatedUsers' : ActorMethod<[], Array<string>>,
  'adminGetUsersWithPasswords' : ActorMethod<[], Array<UserCredential>>,
  'adminGetPlayerWallets' : ActorMethod<[], Array<PlayerWallet>>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'adminTopUpUser' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'drawCard' : ActorMethod<[], bigint>,
  'forceClaimAdmin' : ActorMethod<[string], string>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserInfo' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'playerGetBalance' : ActorMethod<[string, string], bigint>,
  'playerLogin' : ActorMethod<[string, string], LoginResult>,
  'playerPlayAviator' : ActorMethod<[string, string, bigint, bigint], AviatorResult>,
  'playerPlayRoulette' : ActorMethod<[string, string, bigint, string, bigint], PlayResult>,
  'playerPlayRouletteMulti' : ActorMethod<[string, string, Array<RouletteBet>], MultiPlayResult>,
  'playerPlayTeenPatti' : ActorMethod<[string, string, bigint], TeenPattiResult>,
  'playAviator' : ActorMethod<[bigint, bigint], AviatorResult>,
  'playHiLo' : ActorMethod<[bigint, string, bigint], HiLoResult>,
  'playRoulette' : ActorMethod<[bigint, string, bigint], PlayResult>,
  'playRouletteMulti' : ActorMethod<[Array<RouletteBet>], MultiPlayResult>,
  'playSlots' : ActorMethod<[bigint], SlotsResult>,
  'playTeenPatti' : ActorMethod<[bigint], TeenPattiResult>,
  'register' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'topUp' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
