/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserStatProfile = IDL.Record({
  'principal' : IDL.Text,
  'balance' : IDL.Nat,
  'totalWagered' : IDL.Nat,
  'totalWon' : IDL.Nat,
});
export const GameStats = IDL.Record({
  'totalWagered' : IDL.Nat,
  'totalPaidOut' : IDL.Nat,
  'playCount' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'rouletteStats' : GameStats,
  'slotsStats' : GameStats,
  'houseProfit' : IDL.Int,
  'hiloStats' : GameStats,
  'totalWagered' : IDL.Nat,
  'totalPaidOut' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Nat,
  'totalWagered' : IDL.Nat,
  'totalWon' : IDL.Nat,
});
export const HiLoResult = IDL.Record({
  'win' : IDL.Bool,
  'message' : IDL.Text,
  'newCard' : IDL.Nat,
  'payout' : IDL.Nat,
});
export const PlayResult = IDL.Record({
  'win' : IDL.Bool,
  'result' : IDL.Nat,
  'message' : IDL.Text,
  'payout' : IDL.Nat,
});
export const SlotsResult = IDL.Record({
  'win' : IDL.Bool,
  'message' : IDL.Text,
  'reels' : IDL.Vec(IDL.Nat),
  'payout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserStatProfile)], ['query']),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminTopUpUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'drawCard' : IDL.Func([], [IDL.Nat], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserInfo' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'playHiLo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [HiLoResult], []),
  'playRoulette' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
  'playSlots' : IDL.Func([IDL.Nat], [SlotsResult], []),
  'register' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'topUp' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserStatProfile = IDL.Record({
    'principal' : IDL.Text,
    'balance' : IDL.Nat,
    'totalWagered' : IDL.Nat,
    'totalWon' : IDL.Nat,
  });
  const GameStats = IDL.Record({
    'totalWagered' : IDL.Nat,
    'totalPaidOut' : IDL.Nat,
    'playCount' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'rouletteStats' : GameStats,
    'slotsStats' : GameStats,
    'houseProfit' : IDL.Int,
    'hiloStats' : GameStats,
    'totalWagered' : IDL.Nat,
    'totalPaidOut' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'balance' : IDL.Nat,
    'totalWagered' : IDL.Nat,
    'totalWon' : IDL.Nat,
  });
  const HiLoResult = IDL.Record({
    'win' : IDL.Bool,
    'message' : IDL.Text,
    'newCard' : IDL.Nat,
    'payout' : IDL.Nat,
  });
  const PlayResult = IDL.Record({
    'win' : IDL.Bool,
    'result' : IDL.Nat,
    'message' : IDL.Text,
    'payout' : IDL.Nat,
  });
  const SlotsResult = IDL.Record({
    'win' : IDL.Bool,
    'message' : IDL.Text,
    'reels' : IDL.Vec(IDL.Nat),
    'payout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserStatProfile)], ['query']),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminTopUpUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'drawCard' : IDL.Func([], [IDL.Nat], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserInfo' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'playHiLo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [HiLoResult], []),
    'playRoulette' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
    'playSlots' : IDL.Func([IDL.Nat], [SlotsResult], []),
    'register' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'topUp' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };