/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserStatProfile = IDL.Record({
  'principal' : IDL.Text,
  'balance' : IDL.Nat,
  'totalWagered' : IDL.Nat,
  'totalWon' : IDL.Nat,
});
export const GameStats = IDL.Record({
  'totalWagered' : IDL.Nat,
  'totalPaidOut' : IDL.Nat,
  'playCount' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'rouletteStats' : GameStats,
  'slotsStats' : GameStats,
  'houseProfit' : IDL.Int,
  'hiloStats' : GameStats,
  'aviatorStats' : GameStats,
  'teenPattiStats' : GameStats,
  'totalWagered' : IDL.Nat,
  'totalPaidOut' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Nat,
  'totalWagered' : IDL.Nat,
  'totalWon' : IDL.Nat,
});
export const LoginResult = IDL.Record({
  'success' : IDL.Bool,
  'balance' : IDL.Nat,
  'message' : IDL.Text,
});
export const PlayerWallet = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
});
export const HiLoResult = IDL.Record({
  'win' : IDL.Bool,
  'message' : IDL.Text,
  'newCard' : IDL.Nat,
  'payout' : IDL.Nat,
});
export const PlayResult = IDL.Record({
  'win' : IDL.Bool,
  'result' : IDL.Nat,
  'message' : IDL.Text,
  'payout' : IDL.Nat,
});
export const RouletteBet = IDL.Record({
  'betType' : IDL.Text,
  'betValue' : IDL.Nat,
  'wager' : IDL.Nat,
});
export const MultiPlayResult = IDL.Record({
  'win' : IDL.Bool,
  'result' : IDL.Nat,
  'message' : IDL.Text,
  'totalPayout' : IDL.Nat,
});
export const SlotsResult = IDL.Record({
  'win' : IDL.Bool,
  'message' : IDL.Text,
  'reels' : IDL.Vec(IDL.Nat),
  'payout' : IDL.Nat,
});
export const AviatorResult = IDL.Record({
  'win' : IDL.Bool,
  'payout' : IDL.Nat,
  'crashPoint' : IDL.Nat,
  'message' : IDL.Text,
});
export const TeenPattiResult = IDL.Record({
  'win' : IDL.Bool,
  'payout' : IDL.Nat,
  'playerCards' : IDL.Vec(IDL.Nat),
  'dealerCards' : IDL.Vec(IDL.Nat),
  'playerRank' : IDL.Nat,
  'dealerRank' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAdjustBalance' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Text], []),
  'adminCreateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserStatProfile)], ['query']),
  'adminGetCreatedUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'adminGetPlayerWallets' : IDL.Func([], [IDL.Vec(PlayerWallet)], ['query']),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminTopUpUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'drawCard' : IDL.Func([], [IDL.Nat], []),
  'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserInfo' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'playerGetBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'playerLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'playerPlayAviator' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [AviatorResult], []),
  'playerPlayRoulette' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
  'playerPlayRouletteMulti' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(RouletteBet)], [MultiPlayResult], []),
  'playerPlayTeenPatti' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [TeenPattiResult], []),
  'playAviator' : IDL.Func([IDL.Nat, IDL.Nat], [AviatorResult], []),
  'playHiLo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [HiLoResult], []),
  'playRoulette' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
  'playRouletteMulti' : IDL.Func([IDL.Vec(RouletteBet)], [MultiPlayResult], []),
  'playSlots' : IDL.Func([IDL.Nat], [SlotsResult], []),
  'playTeenPatti' : IDL.Func([IDL.Nat], [TeenPattiResult], []),
  'register' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'adminGetGameHistory' : IDL.Func([], [IDL.Vec(IDL.Record({'username': IDL.Text, 'game': IDL.Text, 'wager': IDL.Nat, 'payout': IDL.Nat, 'win': IDL.Bool, 'timestamp': IDL.Int}))], ['query']),
  'topUp' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserStatProfile = IDL.Record({
    'principal' : IDL.Text,
    'balance' : IDL.Nat,
    'totalWagered' : IDL.Nat,
    'totalWon' : IDL.Nat,
  });
  const GameStats = IDL.Record({
    'totalWagered' : IDL.Nat,
    'totalPaidOut' : IDL.Nat,
    'playCount' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'rouletteStats' : GameStats,
    'slotsStats' : GameStats,
    'houseProfit' : IDL.Int,
    'hiloStats' : GameStats,
    'aviatorStats' : GameStats,
    'teenPattiStats' : GameStats,
    'totalWagered' : IDL.Nat,
    'totalPaidOut' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'balance' : IDL.Nat,
    'totalWagered' : IDL.Nat,
    'totalWon' : IDL.Nat,
  });
  const LoginResult = IDL.Record({
    'success' : IDL.Bool,
    'balance' : IDL.Nat,
    'message' : IDL.Text,
  });
  const PlayerWallet = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
  });
  const HiLoResult = IDL.Record({
    'win' : IDL.Bool,
    'message' : IDL.Text,
    'newCard' : IDL.Nat,
    'payout' : IDL.Nat,
  });
  const PlayResult = IDL.Record({
    'win' : IDL.Bool,
    'result' : IDL.Nat,
    'message' : IDL.Text,
    'payout' : IDL.Nat,
  });
  const RouletteBet = IDL.Record({
    'betType' : IDL.Text,
    'betValue' : IDL.Nat,
    'wager' : IDL.Nat,
  });
  const MultiPlayResult = IDL.Record({
    'win' : IDL.Bool,
    'result' : IDL.Nat,
    'message' : IDL.Text,
    'totalPayout' : IDL.Nat,
  });
  const SlotsResult = IDL.Record({
    'win' : IDL.Bool,
    'message' : IDL.Text,
    'reels' : IDL.Vec(IDL.Nat),
    'payout' : IDL.Nat,
  });
  const AviatorResult = IDL.Record({
    'win' : IDL.Bool,
    'payout' : IDL.Nat,
    'crashPoint' : IDL.Nat,
    'message' : IDL.Text,
  });
  const TeenPattiResult = IDL.Record({
    'win' : IDL.Bool,
    'payout' : IDL.Nat,
    'playerCards' : IDL.Vec(IDL.Nat),
    'dealerCards' : IDL.Vec(IDL.Nat),
    'playerRank' : IDL.Nat,
    'dealerRank' : IDL.Nat,
    'message' : IDL.Text,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAdjustBalance' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Text], []),
    'adminCreateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserStatProfile)], ['query']),
    'adminGetCreatedUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'adminGetPlayerWallets' : IDL.Func([], [IDL.Vec(PlayerWallet)], ['query']),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminTopUpUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'drawCard' : IDL.Func([], [IDL.Nat], []),
    'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserInfo' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'playerGetBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'playerLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'playerPlayAviator' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [AviatorResult], []),
    'playerPlayRoulette' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
    'playerPlayRouletteMulti' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(RouletteBet)], [MultiPlayResult], []),
    'playerPlayTeenPatti' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [TeenPattiResult], []),
    'playAviator' : IDL.Func([IDL.Nat, IDL.Nat], [AviatorResult], []),
    'playHiLo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [HiLoResult], []),
    'playRoulette' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [PlayResult], []),
    'playRouletteMulti' : IDL.Func([IDL.Vec(RouletteBet)], [MultiPlayResult], []),
    'playSlots' : IDL.Func([IDL.Nat], [SlotsResult], []),
    'playTeenPatti' : IDL.Func([IDL.Nat], [TeenPattiResult], []),
    'register' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'adminGetGameHistory' : IDL.Func([], [IDL.Vec(IDL.Record({'username': IDL.Text, 'game': IDL.Text, 'wager': IDL.Nat, 'payout': IDL.Nat, 'win': IDL.Bool, 'timestamp': IDL.Int}))], ['query']),
  'topUp' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
